// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpeekIO.Presistence.Context;

namespace SpeekIO.Presistence.Migrations
{
    [DbContext(typeof(SpeekIOContext))]
    [Migration("20191002065227_Initialize")]
    partial class Initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SpeekIO.Domain.Entities.Attachment", b =>
                {
                    b.Property<string>("AttachmentGuid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FileName");

                    b.Property<string>("FilePath");

                    b.Property<string>("Id")
                        .IsRequired();

                    b.HasKey("AttachmentGuid");

                    b.HasAlternateKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Attachment","Common");
                });
#pragma warning restore 612, 618
        }
    }
}
